# Netlify configuration for mySahara Web Viewer
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Node version (if needed for any build tools)
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/view"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-XSS-Protection = "1; mode=block"

# Custom domain configuration (add after you get domain)
# [[redirects]]
#   from = "https://www.mysahara.app/*"
#   to = "https://mysahara.app/:splat"
#   status = 301
#   force = true
